(ns mongol-drafts.states.global
  (:require 
   ["package:flutter/material.dart" :as m]
   [virtual-keyboard.options :as keyboard-options]))

(def state
  (atom
   {:tag-viewable false
    :show-keyboard false
    :show-stacked-keyboard false
    :show-drawer-search false
    :show-sub-drawer-search false
    :show-search-diaglog false
    :show-system-keyboard false
    :tag-on-edit false
    :current-layout "mg"
    :draft/tabbar-index 0}))
