(ns mongol-drafts.utils.response
  (:require
   ["dart:convert" :as convert]
   ["package:http/http.dart" :as http]
   [mongol-drafts.utils.toast :as toast]))

(defn response-message [ctx ^http/Response response success-fn]
  (let [response-body (convert/jsonDecode (.-body response))]
    (if (not= 200 (.-statusCode response))
      (toast/show-toast ctx (get-in response-body ["data" "message"]))
      (success-fn response-body))))