(ns mongol-drafts.widgets.search
  (:require
   ["package:flutter/material.dart" :as m]
   ["package:mongol/mongol.dart" :as mgl]
   [cljd.flutter :as f]
   [mongol-drafts.widgets.empty :as empty-content]
   [mongol-drafts.states.global :as global-state]
   [mongol-drafts.states.draft :as draft-state]
   [mongol-drafts.widgets.list :as list-content]))

(declare search-field)

(defn- close-search []
  (swap! global-state/state assoc
         :show-search-dialog false
         :show-stacked-keyboard false))

(defn close-button []
  (f/widget
   :context ctx
   (m/Material
    .color (-> m/Theme (.of ctx) .-colorScheme .-primaryContainer)
    .elevation 2
    .shape (m/CircleBorder)
    .child
    (m/InkWell
     .customBorder (m/CircleBorder)
     .onTap close-search
     .child
     (m/Padding
      .padding (.all m/EdgeInsets 6)
      .child
      (m/Icon m/Icons.cancel_outlined
              .size 28))))))

(defn widget []
  (f/widget
   :context ctx
   :watch [{{:keys [contents is-end]} :drafts
            show-stacked-keyboard :show-stacked-keyboard} global-state/state]
   (m/Positioned
    .top 0
    .left 0
    .right 0
    .bottom (if (true? show-stacked-keyboard) 360 0))
   (m/Material
    .color (-> m/Theme (.of ctx) .-colorScheme .-primaryContainer))
   (m/SafeArea .bottom (not (true? show-stacked-keyboard)))
   (m/Container
    .decoration (m/BoxDecoration
                 .color (-> m/Theme (.of ctx) .-colorScheme .-primaryContainer)
                 .borderRadius
                 (.all m/BorderRadius (.circular m/Radius 6))
                 .border
                 (.all m/Border .width 0.2))
    .margin (.only m/EdgeInsets .left 6 .right 6))
   (m/Row
    .mainAxisAlignment m.MainAxisAlignment/spaceBetween
    .children
    [(m/Column
      .mainAxisAlignment m.MainAxisAlignment/spaceBetween
      .children
      [(m/Material
        .borderRadius (.circular m/BorderRadius 25)
        .child
        (m/InkWell
         .customBorder (m/CircleBorder)
         .child (m/Icon m/Icons.search_outlined
                        .size 28)))
       (search-field)])
     (m/Expanded
      .child
      (if (empty? contents)
        (empty-content/empty-content-view
         {:icon m/Icons.search_off_outlined
          :message "ᠣᠯᠳᠠᠭᠰᠠᠨ ᠦᠭᠡᠢ"})
        (list-content/widget)))])))
  
(defn search-field []
  (f/widget
   :managed [controller (m/TextEditingController)]
   (m/Expanded)
  ;;  (m/Padding
  ;;   .padding (.all m/EdgeInsets 0))
   (mgl/MongolTextField
    .controller controller
    .onChanged (fn [x]
                 (swap! global-state/state assoc :draft-search x)
                 (draft-state/query-drafts x false))
    .autofocus true
    .maxLines 1
    .minLines 1
    .onTap (fn []
             (swap! global-state/state assoc :show-stacked-keyboard true))
    .style (m/TextStyle .fontSize 16)
    .decoration
    (m/InputDecoration
     .suffixIcon
     (m/IconButton .onPressed
                   (fn []
                     (.clear controller)
                     (swap! global-state/state assoc :draft-search "")
                     (draft-state/query-drafts "" false))
                   .icon (m/Icon m/Icons.clear))
     .isDense true
     ;;  Todo : when hintText is present Text cursor position error
      ;; .hintText "Search"
      ;; .contentPadding (.fromLTRB m/EdgeInsets 0 20 0 20)
    ;;  .border (m/OutlineInputBorder
    ;;           .borderSide (m/BorderSide
    ;;                        .width 0.2
    ;;                        .color m.Colors/blueGrey)
    ;;           .borderRadius (.circular m/BorderRadius 10))
    ;;  .focusedBorder (m/OutlineInputBorder
    ;;                  .borderSide (m/BorderSide
    ;;                               .width 0.2
    ;;                               .color m.Colors/blueGrey)
    ;;                  .borderRadius (.circular m/BorderRadius 10))
     ))))
